local plugin = require("md_babel")

describe("setup", function()
  describe("with default config", function()
    it("errors-out on missing path", function()
      assert.has_error(function () plugin.setup() end, "'md_babel_path' value required")
    end)
  end)

  describe("with empty options", function()
    it("errors-out on missing path", function()
      assert.has_error(function () plugin.setup({}) end, "'md_babel_path' value required")
    end)
  end)

  describe("with md_babel_path option", function()
    it("sets global vim variable", function()
      plugin.setup({ md_babel_path = "/path/to/md-babel" })
      assert.are.same(vim.g.md_babel_executable_path, "/path/to/md-babel")
    end)
  end)
end)
